package com.phiintegration.phienum;

public enum PHINormalizeColumnNameEnum {
	NONE,
	UPPER,
	LOWER,
	UNDERSCORE,
	TRIM,
	TRIM_UPPER,
	TRIM_LOWER,
	TRIM_UNDERSCORE,
	TRIM_UPPER_UNDERSCORE,
	TRIM_LOWER_UNDERSCORE,
	TRIM_UNDERSCORE_NOREPEATINGSPACE,
	TRIM_UPPER_UNDERSCORE_NOREPEATINGSPACE,
	TRIM_LOWER_UNDERSCORE_NOREPEATINGSPACE,
	OTHER
}
